#!/bin/bash

# Toggle mute
toggle() {
    pulsemixer --id $(pulsemixer --list-sinks | grep Default | cut -f3 | cut -d, -f 1 | cut -c 6-) --toggle-mute
}

send_notification() {
    notify-send "$1" -h string:x-canonical-private-synchronous:volume -h int:value:0 -u low -i null
}

send_status_notification() {
    MUTED=$(pulsemixer --id $(pulsemixer --list-sinks | grep Default | cut -f3 | cut -d, -f 1 | cut -c 6-) --get-mute)
    SINK=$(pulsemixer --list-sinks | grep Default | cut -f 3 | cut -d, -f 2 | cut -c 8-)
    if [ "$MUTED" == "1" ]; then
        send_notification "$SINK muted"
    else
        send_notification "$SINK unmuted"
    fi
}

toggle
send_status_notification
