#!/bin/bash

export DISPLAY=:0

# xrandr is executed as markus, it won't work with root
exec_cmd () {
    if [[ $EUID -ne 1000 ]]; then
        su markus -c "$1"
    else
        exec $1
    fi
}

# Disabl eDP1 if lid is closed
grep -q closed /proc/acpi/button/lid/LID/state
if [ $? -eq 0 ]; then
    exec_cmd 'xrandr --output eDP1 --off'
    exit
fi

# Enable eDP1 if not enabled (lid is opened)
exec_cmd xrandr | egrep -q "eDP1 connected( primary)? 1920x1080"
if [ $? -ne 0 ]; then
    # Need to execute it twice, as executing it once might lead to incorrect positions
    # (depending on previous configuration)
    exec_cmd 'autorandr --change && autorandr --change' > /dev/null
fi
